# Generated by Django 3.2.6 on 2021-08-21 01:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInsta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('instagram_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('instagram_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PressTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Набор блогеров'), (2, 'Проведение'), (3, 'Завершен')], default=1)),
                ('number_bloggers', models.IntegerField()),
                ('created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ParamSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('sex', models.IntegerField(choices=[(1, 'Мужчина'), (2, 'Женщина')], default=2)),
                ('involvement', models.FloatField(verbose_name='Вовлеченность')),
                ('number_publications', models.IntegerField(verbose_name='Количество публикаций')),
                ('number_subscribers', models.IntegerField(verbose_name='Количество подписчиков')),
                ('number_subscriptions', models.IntegerField(verbose_name='Количество подписок')),
                ('press_tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='letsgoapi.presstour')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPressTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Согласен'), (2, 'В ожидании ответа'), (3, 'Отказался')], default=2)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letsgoapi.blogger')),
                ('press_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letsgoapi.presstour')),
            ],
        ),
        migrations.AddField(
            model_name='blogger',
            name='press_tour',
            field=models.ManyToManyField(through='letsgoapi.MemberPressTour', to='letsgoapi.PressTour'),
        ),
    ]
