# Generated by Django 3.2.6 on 2021-08-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgoapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presstour',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountinsta',
            name='instagram_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accountinsta',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
