# Generated by Django 3.2.6 on 2021-08-21 11:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgoapi', '0003_alter_accountinsta_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='presstour',
            name='involvement',
            field=models.FloatField(null=True, verbose_name='Вовлеченность'),
        ),
        migrations.AddField(
            model_name='presstour',
            name='key_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AddField(
            model_name='presstour',
            name='number_publications',
            field=models.IntegerField(null=True, verbose_name='Количество публикаций'),
        ),
        migrations.AddField(
            model_name='presstour',
            name='number_subscribers',
            field=models.IntegerField(null=True, verbose_name='Количество подписчиков'),
        ),
        migrations.AddField(
            model_name='presstour',
            name='number_subscriptions',
            field=models.IntegerField(null=True, verbose_name='Количество подписок'),
        ),
        migrations.AddField(
            model_name='presstour',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Мужчина'), (2, 'Женщина')], default=2, null=True),
        ),
        migrations.DeleteModel(
            name='ParamSearch',
        ),
    ]
