# Generated by Django 3.2.6 on 2021-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgoapi', '0004_auto_20210821_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presstour',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
