# Generated by Django 3.2.6 on 2021-08-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgoapi', '0005_alter_presstour_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presstour',
            name='key_words',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='presstour',
            name='number_bloggers',
            field=models.IntegerField(null=True),
        ),
    ]
