# Generated by Django 3.2.6 on 2021-08-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgoapi', '0007_auto_20210821_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presstour',
            name='involvement',
        ),
        migrations.RemoveField(
            model_name='presstour',
            name='key_words',
        ),
        migrations.RemoveField(
            model_name='presstour',
            name='number_publications',
        ),
        migrations.RemoveField(
            model_name='presstour',
            name='number_subscribers',
        ),
        migrations.RemoveField(
            model_name='presstour',
            name='number_subscriptions',
        ),
        migrations.RemoveField(
            model_name='presstour',
            name='sex',
        ),
        migrations.AlterField(
            model_name='presstour',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
